// Generated by https://quicktype.io

export interface Tracks {
	href: string;
	items: Item[];
	limit: number;
	next: null;
	offset: number;
	previous: string;
	total: number;
}

export interface Item {
	added_at: string;
	added_by: AddedBy;
	is_local: boolean;
	primary_color: null;
	sharing_info: SharingInfo;
	track: Track;
	video_thumbnail: VideoThumbnail;
}

export interface AddedBy {
	external_urls: ExternalUrls;
	href: string;
	id: string;
	type: AddedByType;
	uri: string;
	name?: string;
}

export interface ExternalUrls {
	spotify: string;
}

export enum AddedByType {
	Artist = 'artist',
	Track = 'track',
	User = 'user',
}

export interface SharingInfo {
	share_id: string;
	share_url: string;
	uri: string;
}

export interface Track {
	album: Album;
	artists: AddedBy[];
	disc_number: number;
	duration_ms: number;
	episode: boolean;
	explicit: boolean;
	external_ids: ExternalIDS;
	external_urls: ExternalUrls;
	href: string;
	id: string;
	is_local: boolean;
	is_playable: boolean;
	name: string;
	popularity: number;
	preview_url: string;
	track: boolean;
	track_number: number;
	type: AddedByType;
	uri: string;
	linked_from?: AddedBy;
}

export interface Album {
	album_type: AlbumTypeEnum;
	artists: AddedBy[];
	external_urls: ExternalUrls;
	href: string;
	id: string;
	images: Image[];
	name: string;
	release_date: string;
	release_date_precision: ReleaseDatePrecision;
	total_tracks: number;
	type: AlbumTypeEnum;
	uri: string;
}

export enum AlbumTypeEnum {
	Album = 'album',
	Single = 'single',
}

export interface Image {
	height: number;
	url: string;
	width: number;
}

export enum ReleaseDatePrecision {
	Day = 'day',
	Year = 'year',
}

export interface ExternalIDS {
	isrc: string;
}

export interface VideoThumbnail {
	url: null;
}

export interface Config {
	clientId: string;
	accessToken: string;
	accessTokenExpirationTimestampMs: number;
	isAnonymous: boolean;
	recaptchaWebPlayerFraudSiteKey: string;
	app_name: string;
	market: string;
	locale: Locale;
	gtmId: string;
	optimizeId: string;
	userCountry: null;
	isPremium: boolean;
	correlationId: string;
	retargetingPixels: RetargetingPixels;
}

export interface Locale {
	locale: string;
	rtl: boolean;
	textDirection: string;
}

export interface RetargetingPixels {
	twitter: string;
	pinterest: string;
	snapchat: string;
}
